#!/usr/bin/python

import os, sys
from helpers import *

if __name__ == '__main__':
  revision = sys.argv[1]
  students = sys.argv[2]

  path = os.path.join("~/spring14/ours", students)
  path = os.path.join(path, "hw0")

  #Change to this directory
  os.chdir(path)

  #Check that we don't have any illegal files in the repository
  fileCheck = checkForIllegalFiles()

  #Check that the code compiles
  compileOut, compileErr = compileCheck()

  #Run this generic script asynchronously so that we can return the compilation
  #results right away
  runProcessAsync(['python', '~/OpenStyleCheck/HMC/CS70/generictest.py'])

  #If we have output from the illegal file check we should print it
  if len(fileCheck) != 0:
    print fileCheck
    print "-"*80

  print "Compilation Results:"
  print compiledOut
  print "Compilation Errors:"
  print compileErr
